# Generated by Django 3.0.7 on 2020-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200624_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sign',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
